# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Snacks
email: kanakoabe5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code Snacks consists of small, consumable pieces of knowledge about code,
  life, art, music, and events.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kanaabe.com" # the base hostname & protocol for your site
twitter_username: kana_abe
github_username:  kanaabe

# Build settings
markdown: kramdown
